# Generated by Django 5.1.7 on 2025-04-24 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('instagram', models.BooleanField(default=False)),
                ('twitter', models.BooleanField(default=False)),
                ('google', models.BooleanField(default=False)),
                ('profile_picture', models.TextField()),
                ('role', models.CharField(default='user', max_length=10)),
            ],
        ),
    ]
