# Generated by Django 5.1.7 on 2025-05-02 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cards',
            fields=[
                ('id_card', models.AutoField(primary_key=True, serialize=False)),
                ('id_user', models.IntegerField()),
                ('cardholder_name', models.CharField(max_length=100)),
                ('card_number', models.CharField(max_length=16, unique=True)),
                ('exp_date', models.DateField()),
            ],
        ),
    ]
