# Generated by Django 5.1.7 on 2025-05-30 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id_order', models.AutoField(primary_key=True, serialize=False)),
                ('id_user', models.IntegerField()),
                ('total_price', models.IntegerField()),
                ('order_status', models.CharField(choices=[('CARRITO', 'En Carrito'), ('PENDING', 'Pendiente'), ('ONWAY', 'En Camino'), ('DELIVERED', 'Entregado'), ('CONFIRMED', 'Confirmado')], default='CARRITO', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='orders_products',
            fields=[
                ('id_order_product', models.AutoField(primary_key=True, serialize=False)),
                ('id_product', models.IntegerField()),
                ('quantity', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.orders')),
            ],
            options={
                'db_table': 'orders_products',
                'unique_together': {('id_order', 'id_product')},
            },
        ),
    ]
