name: orderservice

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Create and start virtual environment
        working-directory: backend/Order
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        working-directory: backend/Order
        run: pip install -r requirements.txt

      - name: Zip artifact for deployment
        working-directory: backend/Order
        run: |
          zip -r ../../release.zip . -x "venv/**"

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_27946C4A73684B71B24B1D0F3E700A04 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_EA19243AB51845F3BF56DCE3DEA8B814 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_9EE99F912A0B4647A0A25C4C7FFCB600 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'orderservice'
          package: .
